version: "3.7"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: patients
    ports:
      - "3311:3311"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:example@db/patients

  frontend:
    build: ./frontend
    stdin_open: true
    ports:
      - "5137:5137"
    volumes:
      - ./frontend:/src
    depends_on:
      - backend
    network_mode: host

volumes:
  db_data:
